// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadXdpFilter returns the embedded CollectionSpec for xdpFilter.
func loadXdpFilter() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_XdpFilterBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load xdpFilter: %w", err)
	}

	return spec, err
}

// loadXdpFilterObjects loads xdpFilter and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*xdpFilterObjects
//	*xdpFilterPrograms
//	*xdpFilterMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadXdpFilterObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadXdpFilter()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// xdpFilterSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpFilterSpecs struct {
	xdpFilterProgramSpecs
	xdpFilterMapSpecs
	xdpFilterVariableSpecs
}

// xdpFilterProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpFilterProgramSpecs struct {
	XdpTorFilter *ebpf.ProgramSpec `ebpf:"xdp_tor_filter"`
}

// xdpFilterMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpFilterMapSpecs struct {
	BlockedIps  *ebpf.MapSpec `ebpf:"blocked_ips"`
	DropCounter *ebpf.MapSpec `ebpf:"drop_counter"`
}

// xdpFilterVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpFilterVariableSpecs struct {
	UnusedBlockedKey   *ebpf.VariableSpec `ebpf:"unused_blocked_key"`
	UnusedBlockedValue *ebpf.VariableSpec `ebpf:"unused_blocked_value"`
	UnusedCounterKey   *ebpf.VariableSpec `ebpf:"unused_counter_key"`
	UnusedCounterValue *ebpf.VariableSpec `ebpf:"unused_counter_value"`
}

// xdpFilterObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadXdpFilterObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpFilterObjects struct {
	xdpFilterPrograms
	xdpFilterMaps
	xdpFilterVariables
}

func (o *xdpFilterObjects) Close() error {
	return _XdpFilterClose(
		&o.xdpFilterPrograms,
		&o.xdpFilterMaps,
	)
}

// xdpFilterMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadXdpFilterObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpFilterMaps struct {
	BlockedIps  *ebpf.Map `ebpf:"blocked_ips"`
	DropCounter *ebpf.Map `ebpf:"drop_counter"`
}

func (m *xdpFilterMaps) Close() error {
	return _XdpFilterClose(
		m.BlockedIps,
		m.DropCounter,
	)
}

// xdpFilterVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadXdpFilterObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpFilterVariables struct {
	UnusedBlockedKey   *ebpf.Variable `ebpf:"unused_blocked_key"`
	UnusedBlockedValue *ebpf.Variable `ebpf:"unused_blocked_value"`
	UnusedCounterKey   *ebpf.Variable `ebpf:"unused_counter_key"`
	UnusedCounterValue *ebpf.Variable `ebpf:"unused_counter_value"`
}

// xdpFilterPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadXdpFilterObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpFilterPrograms struct {
	XdpTorFilter *ebpf.Program `ebpf:"xdp_tor_filter"`
}

func (p *xdpFilterPrograms) Close() error {
	return _XdpFilterClose(
		p.XdpTorFilter,
	)
}

func _XdpFilterClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed xdpfilter_bpfeb.o
var _XdpFilterBytes []byte
